# Generated by Django 4.1.5 on 2023-04-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('price', models.CharField(max_length=122)),
                ('image', models.CharField(max_length=12)),
                ('desc1', models.TextField()),
                ('desc2', models.TextField()),
                ('desc3', models.TextField()),
                ('desc4', models.TextField()),
            ],
        ),
    ]
