# Generated by Django 4.1.5 on 2023-04-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_dilivary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
